js-working
jakwer84/triangle pull request #1
Opened 2017-09-25 16:10 UTC by jakwer84

2017-09-25 18:33 UTC, matwjablonski requested changes

2017-09-25 18:33 UTC, matwjablonski commented on script.js
>  		h = 12;
you need to declare var of `h`

2017-09-25 18:46 UTC, jakwer84 commented on script.js
>  		h = 12;
done

2017-09-26 16:58 UTC, matwjablonski approved these changes

2017-09-26 19:13 UTC, merged